// Landing page text in both languages; the component only picks a side.
export const copy = {
  en: {
    eyebrow: 'Open source · FiveM NUI · WebGL2',
    title1: 'Your NUI can finally',
    title2: 'see the game.',
    lead: 'Real-time blur and liquid glass behind your FiveM interfaces. CSS backdrop-filter cannot see GTA V from inside the NUI; this library can.',
    ctaStart: 'Get started',
    ctaAi: 'Let your AI build it',
    ctaPlay: 'Playground',
    live: 'Everything here is real liquid glass from the library, refracting a live WebGL city. In FiveM, the city is your game.',
    hudTitle: 'Inventory',
    hudWeight: '12.4 / 40 kg',
    gem: 'gem lens',
    kaleido: 'kaleidoscope',
    problemTitle: 'backdrop-filter cannot see the game.',
    problemText: 'In FiveM the page is transparent and GTA V is drawn underneath it afterwards. CSS has nothing to blur, so your glass becomes a flat box. Drag the handle.',
    before: 'CSS backdrop-filter in FiveM',
    beforeNote: 'flat, dead box',
    after: 'mri-fivem-liquid-glass',
    afterNote: 'the game, blurred and bent, live',
    forTitle: 'What it is for',
    forText: 'Any screen your players open over the game.',
    uses: [
      ['Inventories', 'Frosted panels, liquid slots, text that stays readable over any scene.'],
      ['HUD and gauges', 'Speedometers, status pills and docks that feel part of the world.'],
      ['Interaction menus', 'Third eye and radial menus floating over the scene behind them.'],
      ['Phones and tablets', 'Device screens with the city glowing through the glass.'],
      ['Pause and loading', 'Full screen glass that keeps the game alive behind the menu.'],
      ['Notifications', 'Toasts and prompts that do not cover the action.'],
    ],
    howTitle: 'How it works',
    how: [
      ['Grab the frame', 'The Cfx.re NUI hook hands the live game frame to WebGL.'],
      ['Blur on the GPU', 'A quarter size copy, short gaussian passes, temporal smoothing.'],
      ['Follow your element', 'A distance field of each box: radius, opacity, clipping.'],
      ['Bend the light', 'Liquid rim, color split, highlight, gem facets, kaleidoscope.'],
    ],
    startTitle: 'Running in 60 seconds',
    startText: 'Install, start once, mark your elements. Or let your AI agent do it.',
    aiTitle: 'Or let your AI do it',
    aiText: 'One command teaches Claude Code, Codex, Cursor or Copilot the whole library.',
    aiLink: 'Open the AI onboarding',
    stats: [['0.00 ms', 'resmon'], ['~18 KB', 'minified'], ['0', 'dependencies'], ['MIT', 'license']],
    communityTitle: 'Built in the open',
    communityText: 'Share a preset, add your server to the showcase, or send an improvement. Docs and registry pull requests merge by themselves when CI passes.',
    showcase: 'Showcase',
    presets: 'Presets',
    docs: 'Read the docs',
  },
  pt: {
    eyebrow: 'Open source · NUI do FiveM · WebGL2',
    title1: 'Sua NUI finalmente',
    title2: 'enxerga o jogo.',
    lead: 'Blur e liquid glass em tempo real atrás das suas interfaces do FiveM. O backdrop-filter do CSS não enxerga o GTA V de dentro da NUI; esta biblioteca enxerga.',
    ctaStart: 'Começar',
    ctaAi: 'Deixe a IA fazer',
    ctaPlay: 'Playground',
    live: 'Tudo aqui é liquid glass de verdade da biblioteca, refratando uma cidade WebGL ao vivo. No FiveM, a cidade é o seu jogo.',
    hudTitle: 'Inventário',
    hudWeight: '12,4 / 40 kg',
    gem: 'lente gema',
    kaleido: 'caleidoscópio',
    problemTitle: 'O backdrop-filter não enxerga o jogo.',
    problemText: 'No FiveM a página é transparente e o GTA V é desenhado por baixo depois. O CSS não tem o que desfocar, e o seu vidro vira uma caixa lisa. Arraste a alça.',
    before: 'backdrop-filter do CSS no FiveM',
    beforeNote: 'caixa lisa, morta',
    after: 'mri-fivem-liquid-glass',
    afterNote: 'o jogo, desfocado e entortado, ao vivo',
    forTitle: 'Pra que serve',
    forText: 'Qualquer tela que o jogador abre por cima do jogo.',
    uses: [
      ['Inventários', 'Painéis foscos, slots liquid, texto legível sobre qualquer cena.'],
      ['HUD e medidores', 'Velocímetro, status e docks que parecem parte do mundo.'],
      ['Menus de interação', 'Third eye e radial flutuando sobre a cena atrás deles.'],
      ['Celular e tablet', 'Telas de aparelho com a cidade brilhando através do vidro.'],
      ['Pause e loading', 'Vidro em tela cheia que mantém o jogo vivo atrás do menu.'],
      ['Notificações', 'Avisos que não escondem a ação.'],
    ],
    howTitle: 'Como funciona',
    how: [
      ['Pega o frame', 'O hook da NUI da Cfx.re entrega o frame do jogo ao WebGL.'],
      ['Desfoca na GPU', 'Cópia em 1/4, passadas gaussianas curtas, suavização no tempo.'],
      ['Segue o elemento', 'Um campo de distância de cada caixa: raio, opacidade, corte.'],
      ['Entorta a luz', 'Bisel liquid, separação de cor, brilho, facetas, caleidoscópio.'],
    ],
    startTitle: 'Rodando em 60 segundos',
    startText: 'Instale, inicie uma vez, marque os elementos. Ou deixe o seu agente de IA fazer.',
    aiTitle: 'Ou deixe a IA fazer',
    aiText: 'Um comando ensina a biblioteca inteira pro Claude Code, Codex, Cursor ou Copilot.',
    aiLink: 'Abrir o onboarding de IA',
    stats: [['0,00 ms', 'resmon'], ['~18 KB', 'minificado'], ['0', 'dependências'], ['MIT', 'licença']],
    communityTitle: 'Feito em aberto',
    communityText: 'Compartilhe um preset, coloque o seu servidor na vitrine ou mande uma melhoria. PRs de docs e do registro entram sozinhos quando o CI passa.',
    showcase: 'Vitrine',
    presets: 'Presets',
    docs: 'Ler a documentação',
  },
}

export type Lang = keyof typeof copy
