// Landing text in both languages.
export const copy = {
  en: {
    title: 'Glass that sees the game.',
    lead: 'Real blur and liquid glass behind your FiveM NUI. CSS backdrop-filter cannot see GTA V from inside the page. This library can.',
    start: 'Get started',
    watch: 'Watch it in game',
    lens: 'This lens is the library itself, bending a real GTA V frame. Click it to change the lens.',
    inGameTitle: 'Shot in game, not mocked up.',
    stills: [
      ['A diamond gem catching the sunset', 'Faceted lens, each face bending the sky its own way.'],
      ['Downtown through a cut gem', 'The skyline split into prisms behind the player.'],
      ['A kaleidoscope over the trees', 'Whatever is behind the element, mirrored into slices.'],
    ],
    whyTitle: 'Why backdrop-filter fails in FiveM',
    whyText: [
      'FiveM draws your NUI page on top of the game, and the page itself is transparent. The game is composited underneath it afterwards, so from inside the page there is nothing behind your panel to blur.',
      'The result is the box on the left. This library pulls the live game frame into the page through the Cfx.re NUI hook and draws the glass on the GPU, in the exact shape of your element.',
    ],
    before: 'backdrop-filter in FiveM',
    after: 'mri-fivem-liquid-glass',
    useTitle: 'Three lines in your NUI',
    promptLabel: 'Or paste this into any AI agent, in your project:',
    prompt: 'Where this FiveM NUI blurs the game behind a panel, use mri-fivem-liquid-glass instead of backdrop-filter: read https://mur4i.github.io/mri-fivem-liquid-glass/llms.txt and follow it.',
    copy: 'Copy prompt',
    copied: 'Copied',
    useNote: 'Want the agent to remember it for good? One command teaches it the whole library:',
    aiLink: 'See the AI setup',
    proof: 'resmon at 0.00 ms in game, no measurable FPS drop, about 18 KB, no dependencies, MIT.',
    proofLink: 'How it was measured',
    endTitle: 'Open source, built in the open.',
    endText: 'Made by Murai and the MRI Brasil team. Share a preset, add your server to the showcase or send an improvement.',
    docs: 'Read the docs',
    playground: 'Open the playground',
  },
  pt: {
    title: 'Vidro que enxerga o jogo.',
    lead: 'Blur e liquid glass de verdade atrás da sua NUI do FiveM. O backdrop-filter do CSS não enxerga o GTA V de dentro da página. Esta biblioteca enxerga.',
    start: 'Começar',
    watch: 'Ver no jogo',
    lens: 'Esta lente é a própria biblioteca, entortando um frame real do GTA V. Clique pra trocar a lente.',
    inGameTitle: 'Gravado no jogo, não montado.',
    stills: [
      ['Um diamante gema pegando o pôr do sol', 'Lente lapidada, cada face entortando o céu do seu jeito.'],
      ['O centro da cidade por uma gema', 'Os prédios divididos em prismas atrás do personagem.'],
      ['Um caleidoscópio sobre as árvores', 'O que estiver atrás do elemento, espelhado em fatias.'],
    ],
    whyTitle: 'Por que o backdrop-filter falha no FiveM',
    whyText: [
      'O FiveM desenha a sua página NUI por cima do jogo, e a página é transparente. O jogo é composto por baixo dela depois, então de dentro da página não existe nada atrás do painel pra desfocar.',
      'O resultado é a caixa da esquerda. Esta biblioteca traz o frame do jogo pra dentro da página pelo hook da NUI da Cfx.re e desenha o vidro na GPU, no formato exato do seu elemento.',
    ],
    before: 'backdrop-filter no FiveM',
    after: 'mri-fivem-liquid-glass',
    useTitle: 'Três linhas na sua NUI',
    promptLabel: 'Ou cole isto em qualquer agente de IA, dentro do seu projeto:',
    prompt: 'Onde esta NUI do FiveM desfoca o jogo atrás de um painel, use o mri-fivem-liquid-glass no lugar do backdrop-filter: leia https://mur4i.github.io/mri-fivem-liquid-glass/llms.txt e siga.',
    copy: 'Copiar prompt',
    copied: 'Copiado',
    useNote: 'Quer que o agente lembre pra sempre? Um comando ensina a biblioteca inteira pra ele:',
    aiLink: 'Ver a configuração de IA',
    proof: 'resmon em 0,00 ms no jogo, sem queda de FPS mensurável, uns 18 KB, sem dependências, MIT.',
    proofLink: 'Como foi medido',
    endTitle: 'Open source, feito em aberto.',
    endText: 'Feito pelo Murai e pela equipe MRI Brasil. Compartilhe um preset, coloque o seu servidor na vitrine ou mande uma melhoria.',
    docs: 'Ler a documentação',
    playground: 'Abrir o playground',
  },
}

export type Lang = keyof typeof copy
